version: "3"
networks:
  app-network: null
services:
  # php service
  backend:
    image: blog-backend-laravel:v1
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  # vue frontend

  # nginx service
  webserver:
    image: nginx:1.21.1
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      # - frontend
    networks:
      - app-network

  # mysql
  db_mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: db_blog
      MYSQL_USER: haunc
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: mysqld --sql_mode=""
    networks:
      - app-network
